host: 0.0.0.0

description: | 
  I am an audiovisual artist interested in the relationship between music and place. Through sonic explorations, film making and intermedial VJ techniques, my practice sits at the intersection of music and the moving image.

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  av_projects:
    output: true
  av_sketches:
    output: true
  music:
    output: true
  vj:
    output: true
  radio:
    output: true
  videography:
    output: true
  blog:
    output: true

defaults:
  - scope:
      path: ""
      type: "av_projects"
    values:
      layout: "av_project"
  - scope:
      path: ""
      type: "av_projects"
    values:
      layout: "music"
  - scope:
      path: ""
      type: "videography"
    values:
      layout: "video"
  - scope:
      path: ""
      type: "music"
    values:
      layout: "music"
  - scope:
      path: ""
      type: "radio"
    values:
      layout: "radio"
  - scope:
      path: ""
      type: "vj"
    values:
      layout: "vj"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"